### ISSUE TITLE
0.5.1 I don't understand the error I got

### ISSUE THREAD

**Issue by fxj483** [abjer/isds2020#21]
Hi, I got a very complicated error for 0.5.1.
Here is my code
![image](https://user-images.githubusercontent.com/68167571/89566644-c8583b00-d820-11ea-9501-b5a6c6afd49b.png)
This is the error I got, a super long error:
![image](https://user-images.githubusercontent.com/68167571/89567172-82e83d80-d821-11ea-834f-f57f3ee1ad30.png)
![image](https://user-images.githubusercontent.com/68167571/89567200-909dc300-d821-11ea-8a5d-5d3eff082287.png)
![image](https://user-images.githubusercontent.com/68167571/89567216-95627700-d821-11ea-807f-2de7e4faa513.png)
![image](https://user-images.githubusercontent.com/68167571/89567227-998e9480-d821-11ea-8c20-3c8d57b569f7.png)

the weird thing is when I tried to re-execute my codes for exercise 0.4.1. The same error occurred while I have passed the assertation for exercise 0.4.1 before 
![image](https://user-images.githubusercontent.com/68167571/89567540-21749e80-d822-11ea-9c48-0ee57c875015.png)

Thank you in advance!

**Comment by TomGaut** [comment]
Hey,

So you need to use the 'f' function in order to make the url function work properly. Instead of using (), check out the earlier example and notice that they use {}.

Hope it helps!

**Comment by fxj483** [comment]
@TomGaut Thank you so much! I solved the problem by using the "f" function!
