### ISSUE TITLE
Not assigned to a group

### ISSUE THREAD

**Issue by Rasmusjj** [abjer/isds2020#23]
It seems, that I have not been assigned to any group. I prefered on campus teaching, so for the exercise at 11 should I just attend one of the classes? 
- Rasmus Juul Jørgensen

**Comment by jsr-p** [comment]
hi @Rasmusjj,
you have been allocated to group 16 (check the updated page on Absalon).
This means that you should attend the exercise class in room CSS 2-0-42.
