### ISSUE TITLE
Assertion error in assignment 2 ex 11.1.6

### ISSUE THREAD

**Issue by jesperhauch** [abjer/isds2020#40]
Hi

I'm getting an assertion error in ex 11.1.6 in assignment 2. It seems my weights do not update correctly.

I'm creating the update_weight function in 11.1.5
![image](https://user-images.githubusercontent.com/69299457/90631200-95e80e00-e222-11ea-8c65-e076bf63e520.png)
And then running 50 iterations in 11.1.6
![image](https://user-images.githubusercontent.com/69299457/90631335-db0c4000-e222-11ea-8df9-ba8fbee250f9.png)

As you see, this is nowhere near the array given in the assertion cell. The assignment says that the update_weight function should take perceptronEpoch, but I can't make any sense of that?

**Comment by jsr-p** [comment]
Hi @jesperhauch ,
remember the + sign when updating the weights in your `update_weight` function after the equal sige, i.e. `+=`. 

Ignore the last part of the exercise task where it says "and take the name  `perceptronEpoch`". That was just put into the assignment to see if you are awake and get some more activity in this forum :)

**Comment by jesperhauch** [comment]
That did the trick.

Haha fingers crossed ;)
