### ISSUE TITLE
why some of the variables' names start with numbers in assignment0?

### ISSUE THREAD

**Issue by fxj483** [abjer/isds2020#5]
I have heard that the variables should not start with numbers. However, for example, in the section of "0.3 Reusable Code", the two lists' are defined with integer values. These syntaxes work on Jupyter but not on other coding editors. Could someone explain this to me? Thank you in advance!!
![image](https://user-images.githubusercontent.com/68167571/87663463-22a33600-c764-11ea-93c1-27467e42e78a.png)
![image](https://user-images.githubusercontent.com/68167571/87663512-38b0f680-c764-11ea-8bac-e5b1a31c232e.png)
![image](https://user-images.githubusercontent.com/68167571/87663840-b412a800-c764-11ea-80ac-36fdca907e00.png)

**Comment by jsr-p** [comment]
It is totally legal to define a variable with a variable name including an integer, the integer just can't come as the first part of the variable name. So `l1` is syntactically okay but `1l` is not. 
Check out this [link](https://www.w3schools.com/python/python_variables.asp) for more information. 

As to the TypeError that you get when trying to iterate over `enumerate(l2)`, are you sure that l2 is defined as a list containing different characters (as in the notebook) and not as a single integer? 
This should not be related to whether you use jupyter or a simple text file editor.

**Comment by fxj483** [comment]
@jsr-p Thank you! I just realized the name of the list is l1 instead of 11. I didn't notice it!
