### ISSUE TITLE
Confusion regarding the actual questions in Assignment 0.

### ISSUE THREAD

**Issue by Willy2606** [abjer/isds2020#9]
Hi,

It may be a silly question/issue, but I'm a little confused regarding which questions you expect us to answer throughout Assignment 0. I feel like there's a lot of rhetorical questions up until 3.0, typically written in italic. Are these meant to be answered? - or do they function like a natural way of writing an introduction?

Anyway, please let me know if this forum is only regarded technical issues, etc.

Thanks.

**Comment by jsr-p** [comment]
Hi @Willy2606, this forum is for anything related to the summer school :) 

The required exercises for the assignment are all the indented exercises with a corresponding code cell where your code should be written together with another code cell consisting of  assert statements. 

<img width="449" alt="sc_exercises" src="https://user-images.githubusercontent.com/49307119/88480839-9c9fa000-cf58-11ea-8e48-6b58ee251b8f.png">

The other "exercises" are implemented to make the learning experience more interactive such that you try the concepts from the videos immediately after having seen them.

**Comment by Willy2606** [comment]
Great, I thought so!

Thanks for the quick reply! :)
